<a href="https://colab.research.google.com/github/sanyam092006/ml_new/blob/main/Day_16_Assignment_Introduction_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [ ]:
import

In [ ]:
import numpy as np
import pandas as pd

# <u>**Problem 1**</u>

### You are given a list of urls. You need to extract the domain name from the urls in another list. Also you need to extract the ending string which the url ends with.

### For example, https://www.example.com/market.php -- In this example, domain name is <code>www.example.com</code> and the ending string is <code>php</code>

In [ ]:
# List of urls
url_list = ['https://blog.hubspot.com/marketing/parts-url',
            'https://www.google.com/enrollments',
            'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html',
            'https://www.programiz.com/python-programming/list']

In [ ]:
# Extract the domains and the ending string. Hint : use the split method for a string

## Next create a pandas dataframe with the above three lists.

In [1]:
import pandas as pd
import pandas as pd

url_list = [
    'https://blog.hubspot.com/marketing/parts-url',
    'https://www.google.com/enrollments',
    'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html',
    'https://www.programiz.com/python-programming/list'
]

domains = []
endings = []

for url in url_list:
    no_protocol = url.split("://")[1]
    domain = no_protocol.split("/")[0]
    domains.append(domain)

    last_component = url.split("/")[-1]
    if '.' in last_component and not last_component.startswith('.'):
        ending_string = last_component.split('.')[-1]
    else:
        ending_string = last_component

    endings.append(ending_string)

df = pd.DataFrame({
    'Original_URL': url_list,
    'Domain_Name': domains,
    'Ending_String': endings
})

df

,Original_URL,Domain_Name,Ending_String
0,https://blog.hubspot.com/marketing/parts-url,blog.hubspot.com,parts-url
1,https://www.google.com/enrollments,www.google.com,enrollments
2,https://pandas.pydata.org/pandas-docs/stable/r...,pandas.pydata.org,html
3,https://www.programiz.com/python-programming/list,www.programiz.com,list

In [ ]:
df

,Url,Domain,Ending_string
0,https://blog.hubspot.com/marketing/parts-url,blog.hubspot.com,parts-url
1,https://www.almabetter.com/enrollments,www.almabetter.com,enrollments
2,https://pandas.pydata.org/pandas-docs/stable/r...,pandas.pydata.org,html
3,https://www.programiz.com/python-programming/list,www.programiz.com,list